### ISSUE TITLE
[BUG] 8bit quantization using wrong packing

### ISSUE THREAD

**Issue by Qubitium** [ModelCloud/GPTQModel#193]
In stacktrace below, we can see that post calibration, the packing stage for 8bit quant is using exllama which does not support 8bit packing. Need to switch to triton v2. 

Reported by @FrederikHandberg 

```
INFO - {'layer': 38, 'module': 'mlp.down_proj', 'avg_loss': '0.2514', 'time': '5.4949'}
INFO - {'layer': 39, 'module': 'self_attn.k_proj', 'avg_loss': '0.0118', 'time': '1.1979'}
INFO - {'layer': 39, 'module': 'self_attn.v_proj', 'avg_loss': '0.0159', 'time': '1.2004'}
INFO - {'layer': 39, 'module': 'self_attn.q_proj', 'avg_loss': '0.0362', 'time': '1.2369'}
INFO - {'layer': 39, 'module': 'self_attn.o_proj', 'avg_loss': '0.0485', 'time': '1.2130'}
INFO - {'layer': 39, 'module': 'mlp.up_proj', 'avg_loss': '0.1912', 'time': '1.3559'}
INFO - {'layer': 39, 'module': 'mlp.gate_proj', 'avg_loss': '0.1762', 'time': '1.3453'}
INFO - {'layer': 39, 'module': 'mlp.down_proj', 'avg_loss': '1.4219', 'time': '5.4637'}
INFO - {'layer': 40, 'module': 'self_attn.k_proj', 'avg_loss': '0.0086', 'time': '1.2064'}
INFO - {'layer': 40, 'module': 'self_attn.v_proj', 'avg_loss': '0.0077', 'time': '1.2014'}
INFO - {'layer': 40, 'module': 'self_attn.q_proj', 'avg_loss': '0.0228', 'time': '1.2299'}
INFO - {'layer': 40, 'module': 'self_attn.o_proj', 'avg_loss': '0.0241', 'time': '1.2327'}
INFO - {'layer': 40, 'module': 'mlp.up_proj', 'avg_loss': '0.1526', 'time': '1.3569'}
INFO - {'layer': 40, 'module': 'mlp.gate_proj', 'avg_loss': '0.1451', 'time': '1.3582'}
INFO - {'layer': 40, 'module': 'mlp.down_proj', 'avg_loss': '0.4116', 'time': '5.7132'}
INFO - Packing model...
Traceback (most recent call last):
  File "/workspace/GPTQModel/fred_quant.py", line 96, in <module>
    model.quantize(calibration_dataset)
  File "/workspace/GPTQModel/gptqmodel/models/base.py", line 164, in quantize
    self._quantize(calibration_dataset, batch_size, autotune_warmup_after_quantized, calibration_enable_gpu_cache)
  File "/workspace/GPTQModel/gptqmodel/models/base.py", line 545, in _quantize
    self.qlinear_kernel = pack_model(
  File "/workspace/GPTQModel/gptqmodel/utils/model.py", line 280, in pack_model
    make_quant(
  File "/workspace/GPTQModel/gptqmodel/utils/model.py", line 149, in make_quant
    new_layer = QuantLinear(
  File "/workspace/GPTQModel/gptqmodel/nn_modules/qlinear/qlinear_exllama.py", line 44, in __init__
    super().__init__(bits=bits, group_size=group_size, sym=sym, desc_act=desc_act, **kwargs)
  File "/workspace/GPTQModel/gptqmodel/nn_modules/qlinear/__init__.py", line 19, in __init__
    raise NotImplementedError(err)
NotImplementedError: <class 'gptqmodel.nn_modules.qlinear.qlinear_exllama.ExllamaQuantLinear'> only supports `[4]` bits: actual bits = `8`
```

**Comment by Qubitium** [comment]
@FrederikHandberg @lukehare 8bit quantization and inference has been fixed on main. 8bit test unit tests have been re-added to validate both quantization and post-quantization quality (ppl).  Please re-open this issue is 8bit is not resolved. 

Note that by default, `BACKEND.TRITON` will be used to run 8bit inference code on gpu. Only other kernel that supports gpu accelerated 8bit is `BACKEND.BITBLAS` (format=GPTQ) but we have not yet tested that.
