### ISSUE TITLE
[BUG] batch_size >= 1 broken due to lateset llama3.1 Transformer changes

### ISSUE THREAD

**Issue by Qubitium** [ModelCloud/GPTQModel#278]
Latest transformers v4.43.0 released today broken `batch_size >= 1` for quantization. We need to fix this asap.

```
Traceback (most recent call last):
  File "/root/python/llama3/8b_instruct.py", line 91, in <module>
    quant_log = model.quantize(calibration_dataset, batch_size=32)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/python/GPTQModel/gptqmodel/models/base.py", line 216, in quantize
    calibration_dataset = self._prepare_dataset_for_quantization(calibration_dataset, batch_size)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/python/GPTQModel/gptqmodel/models/base.py", line 143, in _prepare_dataset_for_quantization
    new_calibration_dataset_batched = [
                                      ^
  File "/root/python/GPTQModel/gptqmodel/models/base.py", line 144, in <listcomp>
    collate_data(new_calibration_dataset[start: start + batch_size], pad_token_id)
  File "/root//python/GPTQModel/gptqmodel/utils/data.py", line 158, in collate_data
    input_ids_blocks[i] = pad_block(input_ids_blocks[i], torch.ones((block_bsz, pad_num)) * pad_token_id)
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: only integer tensors of a single element can be converted to an index
```

**Comment by Qubitium** [comment]
temp fix patched in https://github.com/ModelCloud/GPTQModel/pull/279

real fix coming...

**Comment by Qubitium** [comment]
Core cause of bug is llama 3.1 has:

1. pad token defined in tokenizer map but not set in tokenizer config. strange
2. eos token used as fallback to pad token but eos token id for llalma 3.1 instruct is an array (multiple possible eos tokens)

2 is a bug in GPTQModel and 1 is a semi-bug in llama 3.1 not correctly setting pad token. Also strange is that the pad token string is `<|finetune_right_pad_id|>` since I thought pad token really doesn't care about left/right since they are ignored in attention_mask. Strange. Some models don't even use pad token and just default back to `unk`.
