### ISSUE TITLE
[BUG] TGI does not support DeepSeekCoderV2-gptq 

### ISSUE THREAD

**Issue by Grey4sh** [ModelCloud/GPTQModel#328]
**Describe the bug**

I get the error *Cannot load `gptq` weight for GPTQ -> Marlin repacking, make sure the model is already quantized* when i inference gptq quantized model DeepSeekCoderV2  with Text-generation-inference 2.2.0.

**GPU Info**

A100-80GB * 4

 `config.json` 

```shell
{
  "_name_or_path": "/var/mntpkg/deepseek-coder-v2-instruct",
  "architectures": [
    "DeepseekV2ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_deepseek.DeepseekV2Config",
    "AutoModel": "modeling_deepseek.DeepseekV2Model",
    "AutoModelForCausalLM": "modeling_deepseek.DeepseekV2ForCausalLM"
  },
  "aux_loss_alpha": 0.001,
  "bos_token_id": 100000,
  "eos_token_id": 100001,
  "ep_size": 1,
  "first_k_dense_replace": 1,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 12288,
  "kv_lora_rank": 512,
  "max_position_embeddings": 163840,
  "model_type": "deepseek_v2",
  "moe_intermediate_size": 1536,
  "moe_layer_freq": 1,
  "n_group": 8,
  "n_routed_experts": 160,
  "n_shared_experts": 2,
  "norm_topk_prob": false,
  "num_attention_heads": 128,
  "num_experts_per_tok": 6,
  "num_hidden_layers": 60,
  "num_key_value_heads": 128,
  "pretraining_tp": 1,
  "q_lora_rank": 1536,
  "qk_nope_head_dim": 128,
  "qk_rope_head_dim": 64,
  "quantization_config": {
    "bits": 4,
    "checkpoint_format": "gptq",
    "damp_percent": 0.005,
    "desc_act": true,
    "dynamic_bits": null,
    "group_size": 128,
    "lm_head": false,
    "meta": {
      "quantizer": "gptqmodel:0.9.10-dev0"
    },
    "model_file_base_name": null,
    "model_name_or_path": null,
    "quant_method": "gptq",
    "static_groups": false,
    "sym": true,
    "true_sequential": true
  },
  "rms_norm_eps": 1e-06,
  "rope_scaling": {
    "beta_fast": 32,
    "beta_slow": 1,
    "factor": 40,
    "mscale": 1.0,
    "mscale_all_dim": 1.0,
    "original_max_position_embeddings": 4096,
    "type": "yarn"
  },
  "rope_theta": 10000,
  "routed_scaling_factor": 16.0,
  "scoring_func": "softmax",
  "seq_aux": true,
  "tie_word_embeddings": false,
  "topk_group": 3,
  "topk_method": "group_limited_greedy",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.43.3",
  "use_cache": true,
  "v_head_dim": 128,
  "vocab_size": 102400
}
```
 `quantize_config.json`
```shell
{
  "bits": 4,
  "dynamic_bits": null,
  "group_size": 128,
  "desc_act": true,
  "static_groups": false,
  "sym": true,
  "lm_head": false,
  "damp_percent": 0.005,
  "true_sequential": true,
  "model_name_or_path": "deepseek-coder-v2-instruct-gptq",
  "model_file_base_name": "model",
  "quant_method": "gptq",
  "checkpoint_format": "gptq",
  "meta": {
    "quantizer": "gptqmodel:0.9.10-dev0"
 }
```

**To Reproduce**

```shell
docker run -d \
--gpus '"device=4,5,6,7"' \
--shm-size 1g \
--name $model_name \
-p ${external_port}:80 -v $model_path:/data/CmwCoder \
-e WEIGHTS_CACHE_OVERRIDE="/data/CmwCoder" \
tgi:2.2.0 \
--weights-cache-override="/data/CmwCoder" \
--model-id "/data/CmwCoder" --num-shard $num_shard \
--max-input-length 14000 \
--max-total-tokens 16000 \
--max-batch-prefill-tokens 14000 \
--trust-remote-code \
--quantize gptq
```

**Model/Datasets**

DeepSeekCoderV2-236B-MOE

**Screenshots**

```shell
2024-08-02 03:31:18.315 | INFO     | text_generation_server.utils.import_utils:<module>:75 - Detected system cuda
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type deepseek_v2 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[rank0]: Traceback (most recent call last):

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/gptq/__init__.py", line 153, in get_weights
[rank0]:     qweight = weights.get_tensor(f"{prefix}.qweight")

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 212, in get_tensor
[rank0]:     filename, tensor_name = self.get_filename(tensor_name)

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 193, in get_filename
[rank0]:     raise RuntimeError(f"weight {tensor_name} does not exist")

[rank0]: RuntimeError: weight model.layers.59.self_attn.q_a_proj.qweight does not exist


[rank0]: During handling of the above exception, another exception occurred:


[rank0]: Traceback (most recent call last):

[rank0]:   File "/opt/conda/bin/text-generation-server", line 8, in <module>
[rank0]:     sys.exit(app())

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 118, in serve
[rank0]:     server.serve(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 297, in serve
[rank0]:     asyncio.run(

[rank0]:   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
[rank0]:     return loop.run_until_complete(main)

[rank0]:   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[rank0]:     return future.result()

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 231, in serve_inner
[rank0]:     model = get_model(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 490, in get_model
[rank0]:     return FlashCausalLM(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 898, in __init__
[rank0]:     model = model_class(prefix, config, weights)

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 764, in __init__
[rank0]:     self.model = DeepseekV2Model(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 703, in __init__
[rank0]:     [

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 704, in <listcomp>
[rank0]:     DeepseekV2Layer(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 626, in __init__
[rank0]:     self.self_attn = DeepseekV2Attention(

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 236, in __init__
[rank0]:     weight=weights.get_weights(f"{prefix}.q_a_proj"),

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/weights.py", line 344, in get_weights
[rank0]:     return self.weights_loader.get_weights(self, prefix)

[rank0]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/gptq/__init__.py", line 155, in get_weights
[rank0]:     raise RuntimeError(

[rank0]: RuntimeError: Cannot load `gptq` weight for GPTQ -> Marlin repacking, make sure the model is already quantized
 rank=0
2024-08-02T04:51:40.980892Z ERROR text_generation_launcher: Shard 0 failed to start
2024-08-02T04:51:40.980912Z  INFO text_generation_launcher: Shutting down shards
2024-08-02T04:51:40.983834Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=2
2024-08-02T04:51:40.984152Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=2
2024-08-02T04:51:40.985398Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=1
2024-08-02T04:51:40.985884Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=1
2024-08-02T04:51:41.008435Z  INFO shard-manager: text_generation_launcher: Terminating shard rank=3
2024-08-02T04:51:41.008681Z  INFO shard-manager: text_generation_launcher: Waiting for shard to gracefully shutdown rank=3
2024-08-02T04:51:48.113698Z  INFO shard-manager: text_generation_launcher: shard terminated rank=3
2024-08-02T04:51:48.589678Z  INFO shard-manager: text_generation_launcher: shard terminated rank=2
2024-08-02T04:51:49.291857Z  INFO shard-manager: text_generation_launcher: shard terminated rank=1
Error: ShardCannotStart
```

**Additional context**

I don't  have inference problem with `GPTQMode.from_quantized()`

**Comment by Qubitium** [comment]
Looks like TGI has broken loading for sharded gptq models. Note we do yet officially support TGI nor do we have unit tests for TGI. 

Please post output of "ls -h" of quantized model folder so we can verify model is sharded.

**Comment by Cucunnber** [comment]
> Looks like TGI has broken loading for sharded gptq models. Note we do yet officially support TGI nor do we have unit tests for TGI.
> 
> Please post output of "ls -h" of quantized model folder so we can verify model is sharded.

![gptq](https://github.com/user-attachments/assets/0b0c6603-a434-4f7b-8c6f-414628c0e092)

It did not sharded correctly. Besides, there are only  *config.json, configuration_deepseek.py, modelling_deepseek.py, model.safetensors, quantize_config.json* in the quantized model folder after quantized, I had to copy all the tokenizer files  manually from the oringal model folders.

**Comment by Cucunnber** [comment]
Is this issue related to this error?
![Uploading gptq.png…]()

**Comment by Cucunnber** [comment]
Is this issue related to this error?
![gptq](https://github.com/user-attachments/assets/1fce5478-9651-4bb6-ba9a-17583ed79f40)

**Comment by Grey4sh** [comment]
@Qubitium 

Now TGI has supported for GPTQ-quantized MoE models using MoE Marlin. I still encounter some problems when I tried to deploy DeepSeekV2-gptq which i quantized 3 months ago. Some of the error logs are below
```shell
config = DeepseekV2Config {                                 │ │
[rank7]: │ │                         "_name_or_path":                                 │ │
[rank7]: │ │                       "/var/mntpkg/deepseek-coder-v2-instruct",          │ │
[rank7]: │ │                         "architectures": [                               │ │
[rank7]: │ │                       │   "DeepseekV2ForCausalLM"                        │ │
[rank7]: │ │                         ],                                               │ │
[rank7]: │ │                         "attention_bias": false,                         │ │
[rank7]: │ │                         "attention_dropout": 0.0,                        │ │
[rank7]: │ │                         "auto_map": {                                    │ │
[rank7]: │ │                       │   "AutoConfig":                                  │ │
[rank7]: │ │                       "configuration_deepseek.DeepseekV2Config",         │ │
[rank7]: │ │                       │   "AutoModel":                                   │ │
[rank7]: │ │                       "modeling_deepseek.DeepseekV2Model",               │ │
[rank7]: │ │                       │   "AutoModelForCausalLM":                        │ │
[rank7]: │ │                       "modeling_deepseek.DeepseekV2ForCausalLM"          │ │
[rank7]: │ │                         },                                               │ │
[rank7]: │ │                         "aux_loss_alpha": 0.001,                         │ │
[rank7]: │ │                         "bos_token_id": 100000,                          │ │
[rank7]: │ │                         "eos_token_id": 100001,                          │ │
[rank7]: │ │                         "ep_size": 1,                                    │ │
[rank7]: │ │                         "first_k_dense_replace": 1,                      │ │
[rank7]: │ │                         "hidden_act": "silu",                            │ │
[rank7]: │ │                         "hidden_size": 5120,                             │ │
[rank7]: │ │                         "initializer_range": 0.02,                       │ │
[rank7]: │ │                         "intermediate_size": 12288,                      │ │
[rank7]: │ │                         "kv_lora_rank": 512,                             │ │
[rank7]: │ │                         "max_position_embeddings": 163840,               │ │
[rank7]: │ │                         "moe_intermediate_size": 1536,                   │ │
[rank7]: │ │                         "moe_layer_freq": 1,                             │ │
[rank7]: │ │                         "n_group": 8,                                    │ │
[rank7]: │ │                         "n_routed_experts": 160,                         │ │
[rank7]: │ │                         "n_shared_experts": 2,                           │ │
[rank7]: │ │                         "norm_topk_prob": false,                         │ │
[rank7]: │ │                         "num_attention_heads": 128,                      │ │
[rank7]: │ │                         "num_experts_per_tok": 6,                        │ │
[rank7]: │ │                         "num_hidden_layers": 60,                         │ │
[rank7]: │ │                         "num_key_value_heads": 128,                      │ │
[rank7]: │ │                         "pretraining_tp": 1,                             │ │
[rank7]: │ │                         "q_lora_rank": 1536,                             │ │
[rank7]: │ │                         "qk_nope_head_dim": 128,                         │ │
[rank7]: │ │                         "qk_rope_head_dim": 64,                          │ │
[rank7]: │ │                         "quantization_config": {                         │ │
[rank7]: │ │                       │   "bits": 4,                                     │ │
[rank7]: │ │                       │   "checkpoint_format": "gptq",                   │ │
[rank7]: │ │                       │   "damp_percent": 0.005,                         │ │
[rank7]: │ │                       │   "desc_act": true,                              │ │
[rank7]: │ │                       │   "dynamic_bits": null,                          │ │
[rank7]: │ │                       │   "group_size": 128,                             │ │
[rank7]: │ │                       │   "lm_head": false,                              │ │
[rank7]: │ │                       │   "meta": {                                      │ │
[rank7]: │ │                       │     "quantizer": "gptqmodel:0.9.10-dev0"         │ │
[rank7]: │ │                       │   },                                             │ │
[rank7]: │ │                       │   "model_file_base_name": null,                  │ │
[rank7]: │ │                       │   "model_name_or_path": null,                    │ │
[rank7]: │ │                       │   "quant_method": "gptq",                        │ │
[rank7]: │ │                       │   "static_groups": false,                        │ │
[rank7]: │ │                       │   "sym": true,                                   │ │
[rank7]: │ │                       │   "true_sequential": true                        │ │
[rank7]: │ │                         },                                               │ │
[rank7]: │ │                         "quantize": "gptq",                              │ │
[rank7]: │ │                         "rms_norm_eps": 1e-06,                           │ │
[rank7]: │ │                         "rope_scaling": {                                │ │
[rank7]: │ │                       │   "beta_fast": 32,                               │ │
[rank7]: │ │                       │   "beta_slow": 1,                                │ │
[rank7]: │ │                       │   "factor": 40,                                  │ │
[rank7]: │ │                       │   "mscale": 1.0,                                 │ │
[rank7]: │ │                       │   "mscale_all_dim": 1.0,                         │ │
[rank7]: │ │                       │   "original_max_position_embeddings": 4096,      │ │
[rank7]: │ │                       │   "type": "yarn"                                 │ │
[rank7]: │ │                         },                                               │ │
[rank7]: │ │                         "rope_theta": 10000,                             │ │
[rank7]: │ │                         "routed_scaling_factor": 16.0,                   │ │
[rank7]: │ │                         "scoring_func": "softmax",                       │ │
[rank7]: │ │                         "seq_aux": true,                                 │ │
[rank7]: │ │                         "speculator": null,                              │ │
[rank7]: │ │                         "tie_word_embeddings": false,                    │ │
[rank7]: │ │                         "topk_group": 3,                                 │ │
[rank7]: │ │                         "topk_method": "group_limited_greedy",           │ │
[rank7]: │ │                         "torch_dtype": "bfloat16",                       │ │
[rank7]: │ │                         "transformers_version": "4.45.0",                │ │
[rank7]: │ │                         "use_cache": true,                               │ │
[rank7]: │ │                         "v_head_dim": 128,                               │ │
[rank7]: │ │                         "vocab_size": 102400                             │ │
[rank7]: │ │                       }                                                  │ │
[rank7]: │ │        config_class = <class                                             │ │
[rank7]: │ │                       'text_generation_server.models.custom_modeling.fl… │ │
[rank7]: │ │       default_dtype = torch.bfloat16                                     │ │
[rank7]: │ │              device = device(type='cuda', index=7)                       │ │
[rank7]: │ │               dtype = torch.float16                                      │ │
[rank7]: │ │           filenames = [PosixPath('/data/CmwCoder/model.safetensors')]    │ │
[rank7]: │ │   generation_config = GenerationConfig {                                 │ │
[rank7]: │ │                         "bos_token_id": 100000,                          │ │
[rank7]: │ │                         "do_sample": true,                               │ │
[rank7]: │ │                         "eos_token_id": 100001,                          │ │
[rank7]: │ │                         "temperature": 0.3,                              │ │
[rank7]: │ │                         "top_p": 0.95                                    │ │
[rank7]: │ │                       }                                                  │ │
[rank7]: │ │           head_size = 192                                                │ │
[rank7]: │ │      kv_cache_dtype = torch.float16                                      │ │
[rank7]: │ │    lora_adapter_ids = []                                                 │ │
[rank7]: │ │         model_class = <class                                             │ │
[rank7]: │ │                       'text_generation_server.models.custom_modeling.fl… │ │
[rank7]: │ │            model_id = '/data/CmwCoder'                                   │ │
[rank7]: │ │        num_kv_heads = None                                               │ │
[rank7]: │ │              prefix = ''                                                 │ │
[rank7]: │ │            quantize = 'gptq'                                             │ │
[rank7]: │ │                rank = 7                                                  │ │
[rank7]: │ │            revision = None                                               │ │
[rank7]: │ │                self = <text_generation_server.models.flash_causal_lm.Fl… │ │
[rank7]: │ │                       object at 0x7f0558d4b110>      










File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 562, in <listcomp>
    DeepseekV2Layer(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 496, in __init__
    self.mlp = DeepseekV2MoE(f"{prefix}.mlp", config, moe_layer_cls, weights)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py", line 431, in __init__
    self.moe_layer = moe_layer_cls(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/layers/moe/__init__.py", line 231, in __init__
    self.moe = cls(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/layers/moe/gptq_marlin.py", line 103, in __init__
    self.down_proj = _load_expert_weights_row(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/layers/moe/gptq_marlin.py", line 168, in _load_expert_weights_row
    weight = weights.get_weights_row(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/utils/weights.py", line 391, in get_weights_row
    return self.weights_loader.get_weights_row(self, prefix)
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/layers/marlin/gptq.py", line 220, in get_weights_row
    return repack_gptq_for_marlin(
  File "/opt/conda/lib/python3.11/site-packages/text_generation_server/layers/marlin/gptq.py", line 321, in repack_gptq_for_marlin
    raise ValueError(
ValueError: Number of input features (192) not divisible by group size (128)

```

Is there anything wrong  with my process of quantization?

**Comment by Qubitium** [comment]
There is nothing wrong the quant, the TGI included marlin kernel is missing padding code, we fixed this GTPQModel, that allows it to run with models that have features not perfectly divisible by 128. TGI needs to fix it on their end or you can use our inference code.
