### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by yaldashbz** [ModelCloud/GPTQModel#64]
Hi,

I'm trying to install GPTQModel from the source, but I'm facing this error during import.  Could you please specify the versions which are working for you?
My cuda version is 11.7 (via `nvcc --version`), python 3.10, and also:
`pytorch 2.0.0`,
`g++ 10.4.0`

![image](https://github.com/ModelCloud/GPTQModel/assets/62180624/1dfbf61a-1b1d-4c50-9c2a-d553cdf62f15)

Thanks.

**Comment by Qubitium** [comment]
@yaldashbz  Unit tests are done on python 3.11 + cuda 12.1 + pytorch 2.3.1 but should be compatible with anything python 2.0.0 and up. 

This is a very strange import error.  

Did you get any strange errors or warnings during src compile `pip install -v ./ --no-build-isolation`?

**Comment by FrederikHandberg** [comment]
I had the same a few hours ago, I switched to yesterdays commit and it worked, seems like a new thing? (torch 2.1 cuda 11.8)

**Comment by Qubitium** [comment]
@FrederikHandberg You also experienced the exact libnvcrtc.so import error or slightly diff errors?

@CSY-ModelCloud We may have linking issue due to c++ compat with different python/cuda builds.

**Comment by FrederikHandberg** [comment]
exactly the same ```
Traceback (most recent call last):
  File "/workspace/GPTQModel/fred_quant.py", line 2, in <module>
    from gptqmodel import GPTQModel, QuantizeConfig
  File "/workspace/GPTQModel/gptqmodel/__init__.py", line 1, in <module>
    from .models import GPTQModel
  File "/workspace/GPTQModel/gptqmodel/models/__init__.py", line 1, in <module>
    from .auto import MODEL_MAP, GPTQModel
  File "/workspace/GPTQModel/gptqmodel/models/auto.py", line 4, in <module>
    from .baichuan import BaiChuanGPTQ
  File "/workspace/GPTQModel/gptqmodel/models/baichuan.py", line 1, in <module>
    from .base import BaseGPTQModel
  File "/workspace/GPTQModel/gptqmodel/models/base.py", line 23, in <module>
    from ..utils.bitblas import convert_to_bitblas, prepare_model_for_bitblas_load
  File "/workspace/GPTQModel/gptqmodel/utils/bitblas.py", line 9, in <module>
    from ..nn_modules.qlinear.qlinear_bitblas import QuantLinear as BitBLASQuantLinear
  File "/workspace/GPTQModel/gptqmodel/nn_modules/qlinear/qlinear_bitblas.py", line 15, in <module>
    import bitblas
  File "/usr/local/lib/python3.10/dist-packages/bitblas/__init__.py", line 19, in <module>
    from . import gpu  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/bitblas/gpu/__init__.py", line 7, in <module>
    from .fallback import Fallback  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/bitblas/gpu/fallback.py", line 25, in <module>
    from tvm import tir
  File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/_ffi/__init__.py", line 28, in <module>
    from .base import register_error
  File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/_ffi/base.py", line 78, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/_ffi/base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvrtc.so.12: cannot open shared object file: No such file or directory
```

**Comment by yaldashbz** [comment]
> Did you get any strange errors or warnings during src compile `pip install -v ./ --no-build-isolation`?

@Qubitium No, there were no strange things, just some missed packages in my env. But I'm not sure about the warnings during src compile.

**Comment by Qubitium** [comment]
@yaldashbz  @FrederikHandberg  There are actually two issues here. One we fixed. Second is bitblas compat with Cuda < 12.1. 

To resolve both errors, please:

1. use env with cuda >= 12.1 (we will try to resolve this req in a future release)
2. git clone GPTQModel again and rebuild using `pip intall -v ./ --no-build-isolation`

Or if you can't upgrade to cuda >= 12.1, then you need to:

1. Follow guide from bitblass to compile: https://github.com/microsoft/BitBLAS/blob/main/docs/Installation.md
2. git clone GPTQModel again and rebuild using `pip intall -v ./ --no-build-isolation`

**Comment by Qubitium** [comment]
@yaldashbz @FrederikHandberg  v0.9.1 has been released with all our CI unit test passing. Please try it now and let us know. For env with cuda < 12.1 and with bitblas enabled in quantize_config, you will be prompted to manua src compile bitblas.

**Comment by Qubitium** [comment]
Closing this as resolved with 0.9.1 release. If the issue persist, feel free to re-open this issue.

**Comment by yaldashbz** [comment]
Great!
Thank you so much
