### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'gptqmodel.integration' in GPTQModel 1.4.1

### ISSUE THREAD

**Issue by bhavyajoshi-mahindra** [ModelCloud/GPTQModel#843]
**Describe the bug**
I installed GPTQModel from the source to quantize and infer my custom Qwen2-VL model. But it shows the following error while importing.

**GPU Info**

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Software Info**
OS : Linux
Python : 3.11 (also tried in 3.10)

**Output of**
**pip show gptqmodel torch transformers accelerate triton**
```
Name: gptqmodel
Version: 1.4.1.dev0
Summary: A LLM quantization package with user-friendly apis. Based on GPTQ algorithm.
Home-page: https://github.com/ModelCloud/GPTQModel
Author: ModelCloud
Author-email: qubitium@modelcloud.ai
License: 
Location: /home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages
Requires: accelerate, datasets, device-smi, numpy, packaging, safetensors, setuptools, threadpoolctl, transformers
Required-by: 
---
Name: torch
Version: 2.4.1+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, torchaudio, torchvision
---
Name: transformers
Version: 4.47.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: gptqmodel
---
Name: accelerate
Version: 1.2.0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: zach.mueller@huggingface.co
License: Apache
Location: /home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: gptqmodel
---
Name: triton
Version: 3.0.0
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/triton-lang/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License: 
Location: /home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages
Requires: filelock
Required-by: torch

```

**To Reproduce**
while importing gptqmodel as follows 

`from gptqmodel import GPTQModel, QuantizeConfig`

I got the module not found error: 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> [1](vscode-notebook-cell:?execution_count=2&line=1) from gptqmodel import GPTQModel, QuantizeConfig

File ~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/__init__.py:1
----> [1](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/__init__.py:1) from .models import GPTQModel, get_best_device
      [2](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/__init__.py:2) from .quantization import BaseQuantizeConfig, QuantizeConfig
      [3](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/__init__.py:3) from .utils import BACKEND, get_backend

File ~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/__init__.py:2
      [1](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/__init__.py:1) from ._const import get_best_device
----> [2](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/__init__.py:2) from .auto import MODEL_MAP, GPTQModel
      [3](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/__init__.py:3) from .base import BaseGPTQModel
      [4](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/__init__.py:4) from .definitions import *

File ~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:12
      [9](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:9) from huggingface_hub import list_repo_files
     [10](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:10) from transformers import AutoConfig
---> [12](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:12) from ..integration.integration_vllm import patch_vllm
     [13](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:13) from ..utils import BACKEND, EVAL
     [14](https://file+.vscode-resource.vscode-cdn.net/home/bhavya/Desktop/bhavya/llm/gptqmodel/~/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/gptqmodel/models/auto.py:14) from ..utils.logger import setup_logger

ModuleNotFoundError: No module named 'gptqmodel.integration'
```

Please Help
@Qubitium

**Comment by Qubitium** [comment]
@bhavyajoshi-mahindra Please post complete code. Thanks

**Comment by CSY-ModelCloud** [comment]
hi, we have added __init__.py for integrations package. can you pull codes and reinstall with `pip install -e .` then retry?

**Comment by bhavyajoshi-mahindra** [comment]
I have successfully quantized my Qwen2-VL model, am confused on how to infer the quantized model as I need to pass both text and image to the model rather than just text for which the example is given. 

For instance, I tried to use vLLM for inferencing the model as follows: 

```
from transformers import AutoProcessor
from vllm import LLM, SamplingParams
from qwen_vl_utils import process_vision_info

MODEL_PATH = "/home/bhavya/Desktop/bhavya/llm/qwen2-vl-vinplate/model/qwen2_vl_7b_4bit_gptq"

llm = LLM(
    model=MODEL_PATH,
    limit_mm_per_prompt={"image": 10, "video": 10},
)

sampling_params = SamplingParams(
    temperature=0.1,
    top_p=0.001,
    repetition_penalty=1.05,
    max_tokens=256,
    stop_token_ids=[],
)

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "/home/bhavya/Desktop/bhavya/llm/qwen2-vl-vinplate/test/Vin_2024-01-08_13-50-34.jpg",
                "min_pixels": 224 * 224,
                "max_pixels": 1280 * 28 * 28,
            },
            {"type": "text", "text": "What Vehicle Sr No, Engine No, Model and image_label can be identified in the image?"},
        ],
    },
]
# For video input, you can pass following values instead:
# "type": "video",
# "video": "<video URL>",

processor = AutoProcessor.from_pretrained(MODEL_PATH)
prompt = processor.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)
image_inputs, video_inputs = process_vision_info(messages)

mm_data = {}
if image_inputs is not None:
    mm_data["image"] = image_inputs
if video_inputs is not None:
    mm_data["video"] = video_inputs

llm_inputs = {
    "prompt": prompt,
    "multi_modal_data": mm_data,
}

outputs = llm.generate([llm_inputs], sampling_params=sampling_params)
generated_text = outputs[0].outputs[0].text

print(generated_text)
```

But I am facing issues here. 
https://github.com/vllm-project/vllm/issues/9832

Note: I can successfully load my quantized model using GPTQmodel but not sure how to infer on my text and image.

**Comment by Qubitium** [comment]
@bhavyajoshi-mahindra  Use `model.model` from `GPTQModel.load()`, not not use vllm, and and use the model.model with the same code that you inference with HF transformers. Basically replace whatever model loading code with 

```py
model = GPTQModel.load()
# use model.model + any hf code referenced by Qwen2-VL samples
model.mode.generate(image...)
```

**Comment by bhavyajoshi-mahindra** [comment]
Can you mention what exactly can I pass as parameter in model.model.generate()??

I am trying something like this:

```
from datasets import load_dataset
from transformers import AutoTokenizer, AutoProcessor
from gptqmodel import GPTQModel, QuantizeConfig, get_best_device
from qwen_vl_utils import process_vision_info
from vllm import LLM, SamplingParams


quant_path = "/home/bhavya/Desktop/bhavya/llm/gptqmodel/qwen2-vl-qptq-4bit-vinplate"

tokenizer = AutoTokenizer.from_pretrained(quant_path)
model = GPTQModel.load(quant_path)


messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "/home/bhavya/Desktop/bhavya/llm/qwen2-vl-vinplate/test/Vin_2024-01-08_13-50-34.jpg",
                "min_pixels": 224 * 224,
                "max_pixels": 1280 * 28 * 28,
            },
            {"type": "text", "text": "What Vehicle Sr No, Engine No, Model and image_label can be identified in the image?"},
        ],
    },
]

processor = AutoProcessor.from_pretrained(quant_path)
prompt = processor.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)
image_inputs, video_inputs = process_vision_info(messages)

mm_data = {}
if image_inputs is not None:
    mm_data["image"] = image_inputs
if video_inputs is not None:
    mm_data["video"] = video_inputs

llm_inputs = {
    "prompt": prompt,
    "multi_modal_data": mm_data,
}

sampling_params = SamplingParams(
    temperature=0.1,
    top_p=0.001,
    repetition_penalty=1.05,
    max_tokens=256,
    stop_token_ids=[],
)

outputs = model.model.generate(llm_inputs)
print(outputs)
```
But I got this error: 

```
Traceback (most recent call last):
  File "/home/bhavya/Desktop/bhavya/llm/gptqmodel/qwen2-vl-7b-4bit-gptq-infer.py", line 58, in <module>
    outputs = model.model.generate(llm_inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhavya/anaconda3/envs/gptqmodels/lib/python3.11/site-packages/transformers/generation/utils.py", line 2027, in generate
    batch_size = inputs_tensor.shape[0]
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'
```

**Comment by bhavyajoshi-mahindra** [comment]
It worked!!! 
Thanks a lot!

**Comment by bhavyajoshi-mahindra** [comment]
While loading the quantized model, the log shows 
"You passed a model that is compatible with the Marlin int4*fp16 GPTQ kernel but backend is not BACKEND.MARLIN. We recommend using `backend=BACKEND.MARLIN` to use the optimized Marlin kernels for inference. Example: `model = GPTQModel.from_quantized(..., backend=BACKEND.MARLIN)`."

How do I load the model using BACKEND.MARLIN as the code "model = GPTQModel.from_quantized(quant_path,backend=BACKEND.MARLIN)" shows NameError: name 'BACKEND' is not defined

**Comment by Qubitium** [comment]
> While loading the quantized model, the log shows 
> "You passed a model that is compatible with the Marlin int4*fp16 GPTQ kernel but backend is not BACKEND.MARLIN. We recommend using `backend=BACKEND.MARLIN` to use the optimized Marlin kernels for inference. Example: `model = GPTQModel.from_quantized(..., backend=BACKEND.MARLIN)`."
> 
> How do I load the model using BACKEND.MARLIN as the code "`model = GPTQModel.from_quantized(quant_path,backend=BACKEND.MARLIN)`" shows NameError: name 'BACKEND' is not defined

You can ignore that marlin message. We will auto-select marlin for you. The warning needs to be removed.
